### ISSUE TITLE
Rewards for new applications!

### ISSUE THREAD

**Issue by glasgowm148** [ergoplatform/grow-ergo#16]
We're now starting to see some serious projects starting to come into the space and building their applications.

As a special incentive offer. The first 5 submitted and approved applications will receive 

- upto $1,000 SigUSD for command-line implementation
- upto $2,000 SigUSD for web-based UI

To submit, come to the #development channel in Discord Ergo Platform and let us know, respond below or drop an email at team@ergoplatform.org

See [this post from kushti](https://www.ergoforum.org/t/bounties-for-dapp-examples/2946) for more information

**Comment by ldgaetano** [comment]
is this still available?
