### ISSUE TITLE
Community Engagement

### ISSUE THREAD

**Issue by glasgowm148** [ergoplatform/grow-ergo#5]
Fostering a dedicated and passionate ERGO community by rewarding and recognizing those who go above and beyond to contribute to our social channels.

### Community Engagement:
- **(2) 250 SigUSD awards per month**
- Awarded to top 5 contributors per month as voted by ERGO team members
- Factors such as contributions, activity, engagement, constructiveness, helpfulness, etc.
- Revitalising dead or inactive communities is a big bonus. (Regional Telegrams, Facebook -- See [all our groups](https://github.com/glasgowm148/awesome-ergo/blob/master/pages/community.md))

### Best Comments
- **(5) 100 SigUSD awards per month**
- Best comments as chosen by ERGO team members
- Factors such as insight, enthusiasm, high engagement, humour, constructiveness, etc.

### Rules:
- Be an active participant.
- Contribute positively to the ERGO community and abide by all community rules and guidelines.
- Do not spam the channels — quality of contributions will be the major factor in voting.
- We reserve the right to consider any user not eligible, without reason.
- Track your participation.

**Comment by Dtmdmt** [comment]
Will /r/erg_miners be added to the considered groups? =)
